name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Build APK using Official Buildozer Docker Container
        run: |
          docker run --rm \
            --user 1000:1000 \
            -v ${{ github.workspace }}:/home/user/hostroot \
            kivy/buildozer:latest \
            buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: WordReader-APK
          path: bin/*.apk
