name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Build APK using Buildozer Docker
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/home/user/hostroot
          run: |
            buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: WordReader-APK
          path: bin/*.apk
